FROM maven:3.9-eclipse-temurin-24 AS build
WORKDIR /app
COPY backend/pom.xml .

RUN mvn dependency:go-offline
COPY backend/src ./src 
RUN mvn package -DskipTests

FROM eclipse-temurin:24-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]

RUN echo "SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL"
